### ISSUE TITLE
下载mmcv报错

### ISSUE THREAD

**Issue by yaosx616** [ahyunSeo/EquiSym#1]
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fF44V0/mmcv/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fF44V0/mmcv/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-tungav
         cwd: /tmp/pip-install-fF44V0/mmcv/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-fF44V0/mmcv/setup.py", line 101
        yield from parse_line(line)
                 ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
下载mmcv报错，想问下佬遇到过这个问题吗

**Comment by yaosx616** [comment]
> ERROR: Command errored out with exit status 1: command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fF44V0/mmcv/setup.py'"'"'; **file**='"'"'/tmp/pip-install-fF44V0/mmcv/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-tungav cwd: /tmp/pip-install-fF44V0/mmcv/ Complete output (6 lines): Traceback (most recent call last): File "", line 1, in File "/tmp/pip-install-fF44V0/mmcv/setup.py", line 101 yield from parse_line(line) ^ SyntaxError: invalid syntax ---------------------------------------- ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output. 下载mmcv报错，想问下佬遇到过这个问题吗？

The problem has been solved! Just download mmcv that matches the corresponding CUDA version and torch version!

**Comment by ahyunSeo** [comment]
Thank you
